### ISSUE TITLE
RQ2A.210505.002.2021.05.16.04 Beta Test Results

### ISSUE THREAD

**Issue by bill-in-mtl** [GrapheneOS/beta-feedback#13]
Beta Testing Checklist

Device: Sunfish(Pixel 4A)
Build number: RQ2A.210505.002.2021.05.16.04

Receive incoming calls: Works
Make outgoing phone calls: Works
Receive incoming texts: Works
Send outgoing texts: Works

Internet connectivity: Works
Internet browsing: Works
Vanadium use Works
Video playback: Works
Renders websites: Works

Media playback: Works
Bluetooth Audio Pairing: Works
Bluetooth Audio Playback: Works
Bluetooth Audio Calling: Works
PDF Viewer: Working
Alarms/Timer: n/a

Cameras  (Front and Rear): Works,

Handset Microphones: Works
Handset Speakers: Works

Keyboards: Works

File Browsing: Works
Media Transfer to PC: Works
Application Installs: Works
Switch Between Profiles: n/a
Log Out Profiles: n/a
Seedvault Backups: n/a

**Comment by thestinger** [comment]
Thanks.

**Comment by Peter-Easton** [comment]
# Beta Testing Checklist
**Date:** May 18th, 2021
**Device:** Flame (Pixel 4)
**Build number:** RQ2A.210505.005.2021.05.16.04

**Receive incoming calls:** Works
**Make outgoing phone calls:** Works
**Receive incoming SMS:** Works
**Send outgoing SMS:** Works
**Receive incoming MMS:** Works
**Send outgoing MMS:** Works
**Internet connectivity:** Works
**Internet browsing:** Works
**Vanadium use** Works
 * Video playback: Works
 * Renders websites: Works

**Media playback:** Works
**Bluetooth Audio Pairing:** Works
**Bluetooth Audio Playback:** Works
**Bluetooth Audio Calling:** Works
**PDF Viewer:** Working
**Alarms:** Not Tested
**Timer:** Not Tested
**Cameras (Front and Rear):** Works
**Video:** Works (The bug in selfie video camera on OpenCamera is preexisting and caused by an upstream issue. A workaround is in place.)
**Handset Microphones:** Works
**Handset Speakers:** Works
**USB Devices & Peripherals:**
* USB Mass Storage: Works
* Keyboards: Not Tested
* USB Digital Audio Output: Works 

**File Browsing:** Works
**Media Transfer to PC:** Works
**Application Installs:** Works
**Switch Between Profiles:** Works
**Log Out Profiles:** Works
**Seedvault Backups:** Works

**Other Notes:**
Due to a broken USB adapter I wasn't able to test this as extensively as normal, but everything otherwise looks good, no breakages observed.

Seedvault testing of another profile was not done this test.

The keyboard issue when switching between profiles is known and suspected to be an upstream issue. A workaround is in place.
