### ISSUE TITLE
RQ2A.210505.002.2021.05.29.09

### ISSUE THREAD

**Issue by Peter-Easton** [GrapheneOS/beta-feedback#17]
**Date:** May 30th, 2021
**Device:** Flame (Pixel 4)
**Build number:** RQ2A.210505.002.2021.05.29.09

**Receive incoming calls:** Works
**Make outgoing phone calls:** Works
**Receive incoming SMS:** Works
**Send outgoing SMS:** Works
**Receive incoming MMS:** Works
**Send outgoing MMS:** Works
**Data connectivity:** Works
**Wi-Fi connectivity:** Works
**Internet browsing:** Works
**Vanadium use** Works
 * Video playback: Works
 * Renders websites: Works

**Media playback:** Works
**Bluetooth Audio Pairing:** Works
**Bluetooth Audio Playback:** Works
**Bluetooth Audio Calling:** Works
**PDF Viewer:** Works
**Alarms:** Not Tested
**Timer:** Not Tested
**Cameras (Front and Rear):** Works
**Video:** Works (The bug in selfie video camera on OpenCamera is preexisting and caused by an upstream issue. A workaround is in place.)
**Handset Microphones:** Works
**Handset Speakers:** Works
**USB Devices & Peripherals:**
* USB Mass Storage: Works
* Keyboards: Not Tested
* USB Digital Audio Output: Works 

**File Browsing:** Works
**Media Transfer to PC:** Works
**Application Installs:** Works
**Switch Between Profiles:** Works (The bug in fingerprints being wiped from the enclave when ending session on another profile is not observed on the 4)
**Log Out Profiles:** Works

**Seedvault Backups:**
 * **Owner Profile**: Works
 * **Secondary Profile**: Not Tested

**Customization:** Not Tested

**Other Notes:**
Everything looks good so far. I didn't find anything broken that wasn't broken before.

**Comment by southwestgit** [comment]
Beta Testing Checklist
Date: May 30, 2021
Device: 3a
Build number: RQ2A.210505.002.2021.05.29.09

Receive incoming calls: Yes
Make outgoing phone calls: Yes
Receive incoming texts: Yes
Send outgoing texts: Yes
Internet connectivity: Yes
Internet browsing: Yes
Vanadium use:
 * Video playback: Yes
 * Renders websites: Yes
Media playback: Yes
PDF Viewer: Not Tested
Alarms/Timer: Yes
Cameras (Front and Rear): Yes
Video: Yes
Microphones: Yes
USB Devices & Peripherals: Yes
File Browsing: Works
Media Transfer to PC: Not Tested
Application Installs: Yes
Switch Between Profiles: Yes
Log Out Profiles: Yes

Other Notes:
None.

**Comment by bill-in-mtl** [comment]
Beta Testing Checklist

Device: Sunfish(Pixel 4A)
Build number: RQ2A.210505.002.2021.05.29.09

Receive incoming calls: Works
Make outgoing phone calls: Works
Receive incoming texts: Works
Send outgoing texts: Works

Internet connectivity: Works
Internet browsing: Works
Vanadium use Works
Video playback: Works
Renders websites: Works

Media playback: Works
Bluetooth Audio Pairing: Works
Bluetooth Audio Playback: Works
Bluetooth Audio Calling: Works
PDF Viewer: Working
Alarms/Timer: n/a

Cameras  (Front and Rear): Works,

Handset Microphones: Works
Handset Speakers: Works

Keyboards: Works

File Browsing: Works
Media Transfer to PC: Works
Application Installs: Works
Switch Between Profiles: n/a
Log Out Profiles: n/a
Seedvault Backups: n/a

**Comment by Steven0054** [comment]
Device: bramble (Pixel 4a 5G)
Build number: RQ2A.210505.003.2021.05.19.06

Receive incoming calls: Works (VoLTE, Legacy, and VoWiFi)
Make outgoing phone calls: Works (VoLTE, Legacy, and VoWiFi)
Receive incoming texts: Works
Send outgoing texts: Works
Receive incoming MMS: Works
Send outgoing MMS: Works
Internet connectivity: Works
Internet browsing: Works
Vanadium use:

Video playback: Works (YouTube, Dailymotion, Viprow)

Renders websites: Works (YouTube, Dailymotion, Viprow, duckduckgo, amazon, https://wiki.codeaurora.org/xwiki/bin/QAEP/release)

Media playback: Works (avi/mkv/aac/flac)
PDF Viewer: Works (3 documents)
Bluetooth Audio Pairing: Works
Bluetooth Audio Playback: Works
Bluetooth Audio Calling: Works


Still have other items to test but was unable to finish due to work. I'll  edit the remainder in tomorrow.
